WIFIMANAGER_VERSION = 
WIFIMANAGER_ENABLE_TARBALL = NO
WIFIMANAGER_ENABLE_PATCH = NO

WIFIMANAGER_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
WIFIMANAGER_DEPENDENCIES += wpa_supplicant

$(eval $(cmake-package))

