TEST_BATTERY_VERSION =
TEST_BATTERY_ENABLE_TARBALL = NO
TEST_BATTERY_ENABLE_PATCH = NO

TEST_BATTERY_DEPENDENCIES += test-common

TEST_BATTERY_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
