/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"

ui_manager_t ui_manager;

lv_font_t *fs_sourcehansanssc_bold_16;
lv_font_t *fs_sourcehansanssc_bold_40;
lv_font_t *fs_sourcehansanssc_bold_144;
lv_font_t *fs_sourcehansanssc_bold_126;
lv_font_t *fs_sourcehansanssc_bold_28;
lv_font_t *fs_sourcehansanssc_bold_31;
lv_font_t *fs_sourcehansanssc_bold_36;
lv_font_t *fs_sourcehansanssc_bold_82;
lv_font_t *fs_sourcehansanssc_bold_38;

void ui_init(void)
{
    fs_sourcehansanssc_bold_16 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 16);
    fs_sourcehansanssc_bold_40 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 40);
    fs_sourcehansanssc_bold_144 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 144);
    fs_sourcehansanssc_bold_126 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 126);
    fs_sourcehansanssc_bold_28 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 28);
    fs_sourcehansanssc_bold_31 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 31);
    fs_sourcehansanssc_bold_36 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 36);
    fs_sourcehansanssc_bold_82 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 82);
    fs_sourcehansanssc_bold_38 = ui_font_init(LVGL_FONT_PATH(SourceHanSansSC-Bold-crop.otf), 38);
    if (!fs_sourcehansanssc_bold_16) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_16");
    	return;
    }
    if (!fs_sourcehansanssc_bold_40) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_40");
    	return;
    }
    if (!fs_sourcehansanssc_bold_144) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_144");
    	return;
    }
    if (!fs_sourcehansanssc_bold_126) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_126");
    	return;
    }
    if (!fs_sourcehansanssc_bold_28) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_28");
    	return;
    }
    if (!fs_sourcehansanssc_bold_31) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_31");
    	return;
    }
    if (!fs_sourcehansanssc_bold_36) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_36");
    	return;
    }
    if (!fs_sourcehansanssc_bold_82) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_82");
    	return;
    }
    if (!fs_sourcehansanssc_bold_38) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanssc_bold_38");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, false);

#if USE_DOUBLE_SDL_DISP
    extern void lv_sdl_window_create_test();
    lv_sdl_window_create_test();

    lv_disp_t *disp_0 = lv_display_get_next(NULL);
    lv_disp_t *disp_1 = lv_display_get_next(disp_0);
#endif

#if USE_HOST_DEMO
#if USE_DOUBLE_SDL_DISP
    lv_disp_set_default(disp_0);
#endif
    price_tags_screen_1_create(&ui_manager);
#endif

#if USE_DEVICE_DEMO
#if USE_DOUBLE_SDL_DISP
    lv_disp_set_default(disp_1);
#endif
    price_tags_screen_2_create(&ui_manager);
    progress_screen_create(&ui_manager);

    extern void check_load_assets_create(ui_manager_t *ui);
    check_load_assets_create(&ui_manager);
#endif

#if USE_HOST_DEMO
#if USE_DOUBLE_SDL_DISP
    lv_disp_set_default(disp_0);
#endif
    lv_scr_load(price_tags_screen_1_get(&ui_manager)->obj);
#endif

#if USE_DEVICE_DEMO
#if USE_DOUBLE_SDL_DISP
    lv_disp_set_default(disp_1);
#endif
    lv_scr_load(progress_screen_get(&ui_manager)->obj);
#endif
}
