/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *background;
    lv_obj_t *info_container;
    lv_obj_t *qrcode;
    lv_obj_t *act_time_container;
    lv_obj_t *act_time_label;
    lv_obj_t *start_time_label;
    lv_obj_t *end_timer_label;
    lv_obj_t *line;
    lv_obj_t *contact_info_container;
    lv_obj_t *contact_info_label;
    lv_obj_t *phone_label;
    lv_obj_t *phone_num_label;
    lv_obj_t *addr_label;
    lv_obj_t *container_3;
    lv_obj_t *money_label;
    lv_obj_t *ex_price_container;
    lv_obj_t *ex_price_label;
    lv_obj_t *price_label;
    lv_obj_t *label_18;
    lv_obj_t *discount_container;
    lv_obj_t *discount_detail_container_2;
    lv_obj_t *discount_label_2;
    lv_obj_t *discount_image_2;
    lv_obj_t *discount_detail_container_3;
    lv_obj_t *discount_label_3;
    lv_obj_t *discount_image_3;
    lv_obj_t *discount_detail_container_1;
    lv_obj_t *discount_label_1;
    lv_obj_t *discount_image_1;
    lv_obj_t *title_contianer;
    lv_obj_t *name_contianer;
    lv_obj_t *label_3;
    lv_obj_t *label_4;
    lv_obj_t *label_1;
    lv_obj_t *label_2;
    lv_obj_t *point_1;
    lv_obj_t *point_label_1;
    lv_obj_t *point_2;
    lv_obj_t *point_label_2;
    lv_obj_t *small_point_1;
    lv_obj_t *small_point_2;
    lv_obj_t *small_point_4;
    lv_obj_t *container_12;
} price_tags_screen_t;


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container;
    lv_obj_t *title_label;
    lv_obj_t *progress_label;
    lv_obj_t *progress_bar;
    lv_obj_t *spinner;

    lv_timer_t * timer;         // Progress update timer
    uint32_t start_time;        // Start time
    bool is_loading_complete;   // Whether loading is complete
} progress_screen_t;

typedef struct {
    bool auto_del;
    price_tags_screen_t price_tags_screen_1;
    price_tags_screen_t price_tags_screen_2;
    progress_screen_t progress_screen;
} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline price_tags_screen_t *price_tags_screen_1_get(ui_manager_t *ui)
{
    return &ui->price_tags_screen_1;
}

static inline price_tags_screen_t *price_tags_screen_2_get(ui_manager_t *ui)
{
    return &ui->price_tags_screen_2;
}

static inline progress_screen_t *progress_screen_get(ui_manager_t *ui)
{
    return &ui->progress_screen;
}

void price_tags_screen_1_create(ui_manager_t *ui);
void price_tags_screen_2_create(ui_manager_t *ui);
void progress_screen_create(ui_manager_t *ui);

void progress_screen_set_finish(ui_manager_t *ui);

extern lv_font_t *fs_sourcehansanssc_bold_16;
extern lv_font_t *fs_sourcehansanssc_bold_40;
extern lv_font_t *fs_sourcehansanssc_bold_144;
extern lv_font_t *fs_sourcehansanssc_bold_126;
extern lv_font_t *fs_sourcehansanssc_bold_28;
extern lv_font_t *fs_sourcehansanssc_bold_31;
extern lv_font_t *fs_sourcehansanssc_bold_36;
extern lv_font_t *fs_sourcehansanssc_bold_82;
extern lv_font_t *fs_sourcehansanssc_bold_38;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
