/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "lv_aic_player.h"

void price_tags_screen_2_create(ui_manager_t *ui)
{
    price_tags_screen_t *scr = price_tags_screen_2_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->background
    scr->background = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->background, LVGL_VIDEO_PATH(board2_1_scale.mp4));
    lv_aic_player_set_auto_restart(scr->background, true);
    lv_aic_player_set_cmd(scr->background, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->background, 0, 0);
    lv_obj_set_size(scr->background, 800, 1280);

    // Init scr->info_container
    scr->info_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->info_container, 0, 1157);
    lv_obj_set_size(scr->info_container, 800, 123);
    lv_obj_set_scrollbar_mode(scr->info_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->info_container
    lv_obj_set_style_bg_color(scr->info_container, lv_color_hex(0x452000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qrcode
#if LVGL_VERSION_MAJOR == 8
    scr->qrcode = lv_qrcode_create(scr->info_container, 100, lv_color_hex(0x000000), lv_color_hex(0xffffff));
#else
    scr->qrcode = lv_qrcode_create(scr->info_container);
    lv_qrcode_set_size(scr->qrcode, 100);
    lv_qrcode_set_dark_color(scr->qrcode, lv_color_hex(0x000000));
    lv_qrcode_set_light_color(scr->qrcode, lv_color_hex(0xffffff));
#endif
    lv_qrcode_update(scr->qrcode, "www.artinchip.com", 17);
    lv_obj_set_pos(scr->qrcode, 18, 11);

    // Init scr->act_time_container
    scr->act_time_container = lv_obj_create(scr->info_container);
    lv_obj_set_pos(scr->act_time_container, 137, 12);
    lv_obj_set_size(scr->act_time_container, 30, 100);
    lv_obj_set_scrollbar_mode(scr->act_time_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->act_time_container
    lv_obj_set_style_bg_color(scr->act_time_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->act_time_container, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->act_time_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->act_time_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->act_time_label
    scr->act_time_label = lv_label_create(scr->act_time_container);
    lv_label_set_text(scr->act_time_label, "活\n动\n时\n间");
    lv_label_set_long_mode(scr->act_time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->act_time_label, 5, 3);
    lv_obj_set_size(scr->act_time_label, 21, 88);

    // Set style of scr->act_time_label
    lv_obj_set_style_text_font(scr->act_time_label, fs_sourcehansanssc_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->act_time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->start_time_label
    scr->start_time_label = lv_label_create(scr->info_container);
    lv_label_set_text(scr->start_time_label, "11.01");
    lv_label_set_long_mode(scr->start_time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->start_time_label, 187, 1);
    lv_obj_set_size(scr->start_time_label, 115, 61);

    // Set style of scr->start_time_label
    lv_obj_set_style_text_font(scr->start_time_label, fs_sourcehansanssc_bold_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->start_time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->end_timer_label
    scr->end_timer_label = lv_label_create(scr->info_container);
    lv_label_set_text(scr->end_timer_label, "11.07");
    lv_label_set_long_mode(scr->end_timer_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->end_timer_label, 186, 61);
    lv_obj_set_size(scr->end_timer_label, 115, 61);

    // Set style of scr->end_timer_label
    lv_obj_set_style_text_font(scr->end_timer_label, fs_sourcehansanssc_bold_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->end_timer_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line
    scr->line = lv_obj_create(scr->info_container);
    lv_obj_set_pos(scr->line, 192, 63);
    lv_obj_set_size(scr->line, 100, 3);
    lv_obj_set_scrollbar_mode(scr->line, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->line
    lv_obj_set_style_bg_color(scr->line, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contact_info_container
    scr->contact_info_container = lv_obj_create(scr->info_container);
    lv_obj_set_pos(scr->contact_info_container, 311, 13);
    lv_obj_set_size(scr->contact_info_container, 30, 100);
    lv_obj_set_scrollbar_mode(scr->contact_info_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contact_info_container
    lv_obj_set_style_bg_color(scr->contact_info_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->contact_info_container, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contact_info_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contact_info_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contact_info_label
    scr->contact_info_label = lv_label_create(scr->contact_info_container);
    lv_label_set_text(scr->contact_info_label, "联\n系\n方\n式");
    lv_label_set_long_mode(scr->contact_info_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->contact_info_label, 5, 3);
    lv_obj_set_size(scr->contact_info_label, 21, 86);

    // Set style of scr->contact_info_label
    lv_obj_set_style_text_font(scr->contact_info_label, fs_sourcehansanssc_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->contact_info_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->phone_label
    scr->phone_label = lv_label_create(scr->info_container);
    lv_label_set_text(scr->phone_label, "订购电话:");
    lv_label_set_long_mode(scr->phone_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->phone_label, 359, 21);
    lv_obj_set_size(scr->phone_label, 140, 32);

    // Set style of scr->phone_label
    lv_obj_set_style_text_font(scr->phone_label, fs_sourcehansanssc_bold_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->phone_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->phone_num_label
    scr->phone_num_label = lv_label_create(scr->info_container);
    lv_label_set_text(scr->phone_num_label, "400-9527-952X");
    lv_label_set_long_mode(scr->phone_num_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->phone_num_label, 509, 12);
    lv_obj_set_size(scr->phone_num_label, 282, 61);

    // Set style of scr->phone_num_label
    lv_obj_set_style_text_font(scr->phone_num_label, fs_sourcehansanssc_bold_38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->phone_num_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->addr_label
    scr->addr_label = lv_label_create(scr->info_container);
    lv_label_set_text(scr->addr_label, "水星深海区泰拉瑞亚文化水路XY号");
    lv_label_set_long_mode(scr->addr_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->addr_label, 356, 70);
    lv_obj_set_size(scr->addr_label, 431, 35);

    // Set style of scr->addr_label
    lv_obj_set_style_text_font(scr->addr_label, fs_sourcehansanssc_bold_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->addr_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3
    scr->container_3 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_3, 510, 886);
    lv_obj_set_size(scr->container_3, 305, 286);
    lv_obj_set_scrollbar_mode(scr->container_3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_3
    lv_obj_set_style_bg_color(scr->container_3, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->money_label
    scr->money_label = lv_label_create(scr->container_3);
    lv_label_set_text(scr->money_label, "￥");
    lv_label_set_long_mode(scr->money_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->money_label, 24, 84);
    lv_obj_set_size(scr->money_label, 83, 107);

    // Set style of scr->money_label
    lv_obj_set_style_text_font(scr->money_label, fs_sourcehansanssc_bold_82, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->money_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ex_price_container
    scr->ex_price_container = lv_obj_create(scr->container_3);
    lv_obj_set_pos(scr->ex_price_container, 19, 201);
    lv_obj_set_size(scr->ex_price_container, 91, 57);
    lv_obj_set_scrollbar_mode(scr->ex_price_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->ex_price_container
    lv_obj_set_style_bg_color(scr->ex_price_container, lv_color_hex(0xaf1402), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->ex_price_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->ex_price_container, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->ex_price_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->ex_price_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->ex_price_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->ex_price_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ex_price_label
    scr->ex_price_label = lv_label_create(scr->ex_price_container);
    lv_label_set_text(scr->ex_price_label, "优惠");
    lv_label_set_long_mode(scr->ex_price_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->ex_price_label, 10, 2);
    lv_obj_set_size(scr->ex_price_label, 76, 47);

    // Set style of scr->ex_price_label
    lv_obj_set_style_text_font(scr->ex_price_label, fs_sourcehansanssc_bold_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->ex_price_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->price_label
    scr->price_label = lv_label_create(scr->container_3);
    lv_label_set_text(scr->price_label, "88");
    lv_label_set_long_mode(scr->price_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->price_label, 116, 15);
    lv_obj_set_size(scr->price_label, 176, 197);

    // Set style of scr->price_label
    lv_obj_set_style_text_font(scr->price_label, fs_sourcehansanssc_bold_144, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->price_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_18
    scr->label_18 = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_18, "{单人份}");
    lv_label_set_long_mode(scr->label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_18, 129, 204);
    lv_obj_set_size(scr->label_18, 154, 47);

    // Set style of scr->label_18
    lv_obj_set_style_text_font(scr->label_18, fs_sourcehansanssc_bold_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_18, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_container
    scr->discount_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->discount_container, 154, 75);
    lv_obj_set_size(scr->discount_container, 257, 320);
    lv_obj_set_scrollbar_mode(scr->discount_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->discount_container
    lv_obj_set_style_bg_color(scr->discount_container, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->discount_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->discount_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_detail_container_2
    scr->discount_detail_container_2 = lv_obj_create(scr->discount_container);
    lv_obj_set_pos(scr->discount_detail_container_2, 117, 34);
    lv_obj_set_size(scr->discount_detail_container_2, 70, 269);
    lv_obj_set_scrollbar_mode(scr->discount_detail_container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->discount_detail_container_2
    lv_obj_set_style_bg_color(scr->discount_detail_container_2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->discount_detail_container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_label_2
    scr->discount_label_2 = lv_label_create(scr->discount_detail_container_2);
    lv_label_set_text(scr->discount_label_2, "优\n惠\n多\n多");
    lv_label_set_long_mode(scr->discount_label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->discount_label_2, 17, 55);
    lv_obj_set_size(scr->discount_label_2, 39, 217);

    // Set style of scr->discount_label_2
    lv_obj_set_style_text_font(scr->discount_label_2, fs_sourcehansanssc_bold_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->discount_label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_image_2
    scr->discount_image_2 = lv_img_create(scr->discount_detail_container_2);
    lv_img_set_src(scr->discount_image_2, LVGL_IMAGE_PATH(diamond_red_1.png));
    lv_img_set_pivot(scr->discount_image_2, 50, 50);
    lv_img_set_angle(scr->discount_image_2, 0);
    lv_obj_set_style_img_opa(scr->discount_image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->discount_image_2, 13, 10);

    // Init scr->discount_detail_container_3
    scr->discount_detail_container_3 = lv_obj_create(scr->discount_container);
    lv_obj_set_pos(scr->discount_detail_container_3, 183, 34);
    lv_obj_set_size(scr->discount_detail_container_3, 70, 269);
    lv_obj_set_scrollbar_mode(scr->discount_detail_container_3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->discount_detail_container_3
    lv_obj_set_style_bg_color(scr->discount_detail_container_3, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->discount_detail_container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_label_3
    scr->discount_label_3 = lv_label_create(scr->discount_detail_container_3);
    lv_label_set_text(scr->discount_label_3, "低\n至\n八\n折");
    lv_label_set_long_mode(scr->discount_label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->discount_label_3, 17, 55);
    lv_obj_set_size(scr->discount_label_3, 39, 217);

    // Set style of scr->discount_label_3
    lv_obj_set_style_text_font(scr->discount_label_3, fs_sourcehansanssc_bold_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->discount_label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_image_3
    scr->discount_image_3 = lv_img_create(scr->discount_detail_container_3);
    lv_img_set_src(scr->discount_image_3, LVGL_IMAGE_PATH(diamond_red_1.png));
    lv_img_set_pivot(scr->discount_image_3, 50, 50);
    lv_img_set_angle(scr->discount_image_3, 0);
    lv_obj_set_style_img_opa(scr->discount_image_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->discount_image_3, 13, 10);

    // Init scr->discount_detail_container_1
    scr->discount_detail_container_1 = lv_obj_create(scr->discount_container);
    lv_obj_set_pos(scr->discount_detail_container_1, 48, 34);
    lv_obj_set_size(scr->discount_detail_container_1, 70, 269);
    lv_obj_set_scrollbar_mode(scr->discount_detail_container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->discount_detail_container_1
    lv_obj_set_style_bg_color(scr->discount_detail_container_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->discount_detail_container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_label_1
    scr->discount_label_1 = lv_label_create(scr->discount_detail_container_1);
    lv_label_set_text(scr->discount_label_1, "活\n动\n期\n间");
    lv_label_set_long_mode(scr->discount_label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->discount_label_1, 17, 55);
    lv_obj_set_size(scr->discount_label_1, 39, 217);

    // Set style of scr->discount_label_1
    lv_obj_set_style_text_font(scr->discount_label_1, fs_sourcehansanssc_bold_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->discount_label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->discount_image_1
    scr->discount_image_1 = lv_img_create(scr->discount_detail_container_1);
    lv_img_set_src(scr->discount_image_1, LVGL_IMAGE_PATH(diamond_red_1.png));
    lv_img_set_pivot(scr->discount_image_1, 50, 50);
    lv_img_set_angle(scr->discount_image_1, 0);
    lv_obj_set_style_img_opa(scr->discount_image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->discount_image_1, 13, 10);

    // Init scr->title_contianer
    scr->title_contianer = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->title_contianer, 401, 21);
    lv_obj_set_size(scr->title_contianer, 398, 380);
    lv_obj_set_scrollbar_mode(scr->title_contianer, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->title_contianer
    lv_obj_set_style_bg_color(scr->title_contianer, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->title_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->name_contianer
    scr->name_contianer = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->name_contianer, 42, 36);
    lv_obj_set_size(scr->name_contianer, 312, 313);
    lv_obj_set_scrollbar_mode(scr->name_contianer, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->name_contianer
    lv_obj_set_style_bg_color(scr->name_contianer, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->name_contianer, lv_color_hex(0xaf1402), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->name_contianer, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->name_contianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->name_contianer);
    lv_label_set_text(scr->label_3, "日");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 8, 127);
    lv_obj_set_size(scr->label_3, 125, 153);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, fs_sourcehansanssc_bold_126, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->name_contianer);
    lv_label_set_text(scr->label_4, "料");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 158, 128);
    lv_obj_set_size(scr->label_4, 106, 144);

    // Set style of scr->label_4
    lv_obj_set_style_text_font(scr->label_4, fs_sourcehansanssc_bold_126, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->name_contianer);
    lv_label_set_text(scr->label_1, "家");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 157, -20);
    lv_obj_set_size(scr->label_1, 125, 151);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_sourcehansanssc_bold_126, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->name_contianer);
    lv_label_set_text(scr->label_2, "有");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 18, -25);
    lv_obj_set_size(scr->label_2, 106, 144);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, fs_sourcehansanssc_bold_126, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->point_1
    scr->point_1 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->point_1, 19, 160);
    lv_obj_set_size(scr->point_1, 54, 54);
    lv_obj_set_scrollbar_mode(scr->point_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->point_1
    lv_obj_set_style_bg_color(scr->point_1, lv_color_hex(0xaf1402), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->point_1, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->point_label_1
    scr->point_label_1 = lv_label_create(scr->point_1);
    lv_label_set_text(scr->point_label_1, "正");
    lv_label_set_long_mode(scr->point_label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->point_label_1, 11, 1);
    lv_obj_set_size(scr->point_label_1, 31, 42);

    // Set style of scr->point_label_1
    lv_obj_set_style_text_font(scr->point_label_1, fs_sourcehansanssc_bold_31, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->point_label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->point_2
    scr->point_2 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->point_2, 324, 160);
    lv_obj_set_size(scr->point_2, 54, 54);
    lv_obj_set_scrollbar_mode(scr->point_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->point_2
    lv_obj_set_style_bg_color(scr->point_2, lv_color_hex(0xaf1402), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->point_2, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->point_label_2
    scr->point_label_2 = lv_label_create(scr->point_2);
    lv_label_set_text(scr->point_label_2, "宗");
    lv_label_set_long_mode(scr->point_label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->point_label_2, 12, 2);
    lv_obj_set_size(scr->point_label_2, 31, 42);

    // Set style of scr->point_label_2
    lv_obj_set_style_text_font(scr->point_label_2, fs_sourcehansanssc_bold_31, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->point_label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->small_point_1
    scr->small_point_1 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->small_point_1, 32, 27);
    lv_obj_set_size(scr->small_point_1, 25, 25);
    lv_obj_set_scrollbar_mode(scr->small_point_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->small_point_1
    lv_obj_set_style_bg_color(scr->small_point_1, lv_color_hex(0xc9813a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->small_point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->small_point_1, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->small_point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->small_point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->small_point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->small_point_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->small_point_2
    scr->small_point_2 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->small_point_2, 339, 26);
    lv_obj_set_size(scr->small_point_2, 25, 25);
    lv_obj_set_scrollbar_mode(scr->small_point_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->small_point_2
    lv_obj_set_style_bg_color(scr->small_point_2, lv_color_hex(0xc9813a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->small_point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->small_point_2, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->small_point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->small_point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->small_point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->small_point_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->small_point_4
    scr->small_point_4 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->small_point_4, 340, 332);
    lv_obj_set_size(scr->small_point_4, 25, 25);
    lv_obj_set_scrollbar_mode(scr->small_point_4, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->small_point_4
    lv_obj_set_style_bg_color(scr->small_point_4, lv_color_hex(0xc9813a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->small_point_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->small_point_4, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->small_point_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->small_point_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->small_point_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->small_point_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_12
    scr->container_12 = lv_obj_create(scr->title_contianer);
    lv_obj_set_pos(scr->container_12, 32, 333);
    lv_obj_set_size(scr->container_12, 25, 25);
    lv_obj_set_scrollbar_mode(scr->container_12, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_12
    lv_obj_set_style_bg_color(scr->container_12, lv_color_hex(0xc9813a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_12, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}
