HTTP_WIFICONFIG_VERSION =
HTTP_WIFICONFIG_ENABLE_TARBALL = NO
HTTP_WIFICONFIG_ENABLE_PATCH = NO
HTTP_WIFICONFIG_INSTALL_STAGING = YES
HTTP_WIFICONFIG_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
HTTP_WIFICONFIG_DEPENDENCIES += wifimanager

$(eval $(cmake-package))

